### ISSUE TITLE
add support for comparision syntax

### ISSUE THREAD

**Issue by jkvor** [jkvor/emongo#4]
ie: emongo:find(pool, "collection", [{"age", '>=', 21}])

**Comment by dweldon** [comment]
It would be great to have support for as many of the conditional operators as possible from here: http://www.mongodb.org/display/DOCS/Advanced+Queries
I'm assuming that implementing $exists is the same amount of work as implementing '>='. I'd recommend erlang's conditional evaluation syntax (=< and not <=), and possibly using '/=' instead of $ne.
